# Generated by Django 4.2.7 on 2023-11-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('primary_muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='gym.musclegroup')),
                ('second_muscle_group', models.ManyToManyField(related_name='secondary', to='gym.musclegroup')),
            ],
        ),
    ]
